
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- User roles enum
CREATE TYPE public.user_role AS ENUM ('user', 'admin');

-- Signal direction enum
CREATE TYPE public.signal_direction AS ENUM ('buy', 'sell');

-- Signal status enum
CREATE TYPE public.signal_status AS ENUM ('pending', 'executed', 'cancelled', 'expired');

-- Trade status enum
CREATE TYPE public.trade_status AS ENUM ('open', 'closed', 'cancelled');

-- Strategy status enum
CREATE TYPE public.strategy_status AS ENUM ('active', 'inactive');

-- Profiles table
CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  username text,
  email text,
  phone text,
  role public.user_role NOT NULL DEFAULT 'user',
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

-- User settings / Binance API config
CREATE TABLE public.user_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  binance_api_key text,
  binance_api_secret text,
  bot_enabled boolean NOT NULL DEFAULT false,
  trading_mode text NOT NULL DEFAULT 'spot', -- 'spot' or 'futures'
  min_confidence integer NOT NULL DEFAULT 70,
  stop_loss_pct numeric NOT NULL DEFAULT 2.0,
  take_profit_pct numeric NOT NULL DEFAULT 4.0,
  position_size_pct numeric NOT NULL DEFAULT 5.0,
  max_open_trades integer NOT NULL DEFAULT 5,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE(user_id)
);

-- PineScript strategies
CREATE TABLE public.strategies (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  pinescript_code text NOT NULL,
  ai_interpretation text,
  status public.strategy_status NOT NULL DEFAULT 'inactive',
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Market signals generated by AI scanning
CREATE TABLE public.signals (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  strategy_id uuid REFERENCES public.strategies(id) ON DELETE SET NULL,
  symbol text NOT NULL,
  direction public.signal_direction NOT NULL,
  confidence integer NOT NULL DEFAULT 0, -- 0-100
  entry_price numeric NOT NULL,
  stop_loss numeric,
  take_profit numeric,
  timeframe text NOT NULL DEFAULT '1h',
  reason text,
  status public.signal_status NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Open/closed positions (trades)
CREATE TABLE public.trades (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  signal_id uuid REFERENCES public.signals(id) ON DELETE SET NULL,
  symbol text NOT NULL,
  direction public.signal_direction NOT NULL,
  entry_price numeric NOT NULL,
  exit_price numeric,
  quantity numeric NOT NULL,
  stop_loss numeric,
  take_profit numeric,
  pnl numeric,
  pnl_pct numeric,
  status public.trade_status NOT NULL DEFAULT 'open',
  binance_order_id text,
  opened_at timestamptz NOT NULL DEFAULT NOW(),
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- Market scan results cache
CREATE TABLE public.market_scans (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  symbol text NOT NULL,
  price numeric NOT NULL,
  change_pct_24h numeric NOT NULL,
  volume_24h numeric NOT NULL,
  scan_type text NOT NULL, -- 'gainer' or 'loser'
  signal_direction public.signal_direction,
  confidence integer,
  timeframe text NOT NULL DEFAULT '1h',
  scanned_at timestamptz NOT NULL DEFAULT NOW()
);

-- Trigger: auto-sync profiles on new auth user
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, phone, role)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.phone,
    'user'::public.user_role
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

-- Helper: get user role (SECURITY DEFINER to avoid infinite recursion)
CREATE OR REPLACE FUNCTION get_user_role(uid uuid)
RETURNS user_role
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM profiles WHERE id = uid;
$$;

-- Updated_at auto-update function
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_user_settings_updated_at BEFORE UPDATE ON user_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_strategies_updated_at BEFORE UPDATE ON strategies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_signals_updated_at BEFORE UPDATE ON signals FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_trades_updated_at BEFORE UPDATE ON trades FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ==================
-- RLS POLICIES
-- ==================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_scans ENABLE ROW LEVEL SECURITY;

-- PROFILES
CREATE POLICY "Admins have full access to profiles" ON profiles
  FOR ALL TO authenticated USING (get_user_role(auth.uid()) = 'admin'::user_role);

CREATE POLICY "Users can view their own profile" ON profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id)
  WITH CHECK (role IS NOT DISTINCT FROM get_user_role(auth.uid()));

-- USER SETTINGS
CREATE POLICY "Users can view own settings" ON user_settings
  FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Users can insert own settings" ON user_settings
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own settings" ON user_settings
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own settings" ON user_settings
  FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Admins full access to settings" ON user_settings
  FOR ALL TO authenticated USING (get_user_role(auth.uid()) = 'admin'::user_role);

-- STRATEGIES
CREATE POLICY "Users can view own strategies" ON strategies
  FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Users can insert own strategies" ON strategies
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own strategies" ON strategies
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own strategies" ON strategies
  FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Admins full access to strategies" ON strategies
  FOR ALL TO authenticated USING (get_user_role(auth.uid()) = 'admin'::user_role);

-- SIGNALS
CREATE POLICY "Users can view own signals" ON signals
  FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Users can insert own signals" ON signals
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own signals" ON signals
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own signals" ON signals
  FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Admins full access to signals" ON signals
  FOR ALL TO authenticated USING (get_user_role(auth.uid()) = 'admin'::user_role);

-- TRADES
CREATE POLICY "Users can view own trades" ON trades
  FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Users can insert own trades" ON trades
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own trades" ON trades
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own trades" ON trades
  FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Admins full access to trades" ON trades
  FOR ALL TO authenticated USING (get_user_role(auth.uid()) = 'admin'::user_role);

-- MARKET_SCANS (public read, no user ownership)
CREATE POLICY "Anyone can view market scans" ON market_scans
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Anon can view market scans" ON market_scans
  FOR SELECT TO anon USING (true);

-- Public view for profiles
CREATE VIEW public_profiles AS
  SELECT id, role FROM profiles;
